### ISSUE TITLE
BeQuiet not hiding heads

### ISSUE THREAD

**Issue by SomaTGW** [Xorag/BeQuiet#3]
Currently leveling in BfA, Tiragarde, and the sound gets muted but the heads still appear.
Edit: I had to go into BeQuiet.lua and change BQ_SHOW_HEADS = true to BQ_SHOW_HEADS = 0 for it to hide heads.

**Comment by Xorag** [comment]
this is all customizable logic, you might need a fresh install/config, if you've somehow whitelisted certain areas etc...

**Comment by SomaTGW** [comment]
> this is all customizable logic, you might need a fresh install/config, if you've somehow whitelisted certain areas etc...

After a clean install, a head still showed up In Defenses of the Exodar
Whitelist is completely empty, hide heads was on but the lua file was BQ_SHOW_HEADS = true no matter what I did.
Also tried disable and enable hide heads with no success.

**Comment by Xorag** [comment]
ill take a look when we get to the prepatch and likely need to update the addon at that time

**Comment by Xorag** [comment]
ive started with a fresh config file and flown around tiragarde and other areas but i don't see this behavior

**Comment by SomaTGW** [comment]
I still sometimes get talking heads, it seems to happen mostly in combat now though which most addons tends to not like most of the time.

**Comment by Xorag** [comment]
I haven't experienced any unexpected behavior with bequiet since WW launch. if you get any lua errors i can maybe take a look, otherwise i'd have to suspect an addon conflict which would be unlikely, or possibly some client configuration/performance issue i've never seen
