### ISSUE TITLE
Whitelist all dungeons as a category?

### ISSUE THREAD

**Issue by Bogdanov89** [Xorag/BeQuiet#4]
Thank you for this amazing addon!
I am sorry for this beginner question, i just started using the addon.

Would it please be possible to have a single command to whitelist all the dungeons in WoW, so that their talking heads are heard/seen?
Or at least the dungeons in the current expansion, if all would be too much to implement.

Blizzard sometimes puts some crucial instructions for movement/directions via these talking heads in dungeons (like in the Dawnbreaker dungeon), and dungeons that have nothing important can just be blacklisted individually.

Thanks!

**Comment by Xorag** [comment]
Anything is possible, however the addon does have whitelisting functionality, and there are only ~8 dungeons per expansion/season. 

My suggestion with this addon is to always turn it off when you first do content, especially in a new expansion. When you're ready to turn it back on, the whitelist button is just one click away.

This dungeon, unlike something like the withered army training is static. Everything happens the same every time. Once you learn it you won't need the talking heads anymore (or just whitelist the dungeon).

The feature request is valid and in the future I might look at doing some more categorization/automation but I have no plans at this time.

Thanks for using it :)

**Comment by Bogdanov89** [comment]
Thank you for explaining and considering it!
