### ISSUE TITLE
Occasional LUA error

### ISSUE THREAD

**Issue by rwygand** [Xorag/BeQuiet#5]
5x [ADDON_ACTION_BLOCKED] AddOn 'BeQuiet' tried to call the protected function 'Frame:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@WorldQuestTracker/WorldQuestTracker_Core.lua"]:1452: in function `ShowLine'
[string "@WorldQuestTracker/WorldQuestTracker_Core.lua"]:1566: in function <WorldQuestTracker/WorldQuestTracker_Core.lua:1547>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

I'm unsure if this is due to WQT or BeQuiet or their interaction.

**Comment by Xorag** [comment]
Yea the lines of code the error references is for world quest tracker, and BeQuiet doesn't call the referenced protected functions, it looks like the error is somehow being misattributed to BeQuiet

**Comment by rwygand** [comment]
Okay, I'll close this issue and bring it up over on WQT's github. Thanks.
