### ISSUE TITLE
Illidan muted on quest "Moments of Reflection"

### ISSUE THREAD

**Issue by paulhoux** [Xorag/BeQuiet#7]
During the quest [Moments of Reflection](https://www.wowhead.com/quest=49077/moments-of-reflection) the voice of Illidan can not be heard if talking heads are muted.

I whitelisted the specific areas on the map to hear what he had to say. These areas are:

Lorlathil (in Val'sharah)
Temple of Elune (in Val'sharah)
Nordrassil in Mount Hyjal

Perhaps these areas can be automatically unmounted if someone is on this quest?

**Comment by Xorag** [comment]
I can't possibly maintain a list of quests/situations where people might want to hear the dialog, my suggestion is always to disable the addon temporarily during new patches/story quest content just in case.
