### ISSUE TITLE
Talking Heads still persist

### ISSUE THREAD

**Issue by martin-doychinov** [Xorag/BeQuiet#8]
I've reinstalled the addon, deleted saved variables both through Curseforge and manually, deleted my cache and the talking head panel still appears.

When I use the `/bq on` command in game it displays the message saying that it is now blocking talking heads. Immediately after that I use `/bq` to list the status of the options and that says "talking heads are currently shown" no matter how many times I repeat.

![image](https://github.com/user-attachments/assets/ba03ea87-980c-49bc-85bd-336c6daf4228)

An interesting thing I've noticed happening is that if I fly over a world quest, the talking head will appear once, then on subsequent flyovers the talking head will not appear again.

**Comment by Xorag** [comment]
Post your lua config

**Comment by Xorag** [comment]
It looks like that final message shows "shown" no matter what probably a logic error but shouldn't affect the actual functionality

**Comment by martin-doychinov** [comment]
> Post your lua config

Which file do you mean? The Options.lua?

**Comment by Xorag** [comment]
bequiet.lua in the WTF folder

**Comment by martin-doychinov** [comment]
`
ENABLED = 1

VERBOSE = 1
WHITELIST = {
"Crestfall",
"Falanaar Tunnels",
"Havenswood",
"Jorundall",
"Molten Cay",
"Orgrimmar",
"Shattered Locus",
"Skittering Hollow",
"Snowblossom Village",
"Stormwind City",
"Temple of Fal'adora",
"The Dread Chain",
"The Rotting Mire",
"Torghast, Tower of the Damned",
"Un'gol Ruins",
"Valdrakken",
"Verdant Wilds",
"Whispering Reef",
}
BLACKLIST = {
}
VO_ENABLED = 0
BQ_SHOW_HEADS = true
BQ_SUPPRESS_INSTANCES = false
`

**Comment by martin-doychinov** [comment]
I deleted this file before posting (before opening the issue I mean).

I also tried to reset the whitelist through the ingame commands but it seems it has not worked.

Just now I tried manually setting `BQ_SHOW_HEADS` to false by editing the file and logged on to test, still showing talking heads.

**Comment by Xorag** [comment]
your config is the same as mine, the refactor we did some time ago i think makes the variable values/names confusing and might need to be cleaned up but you shouldn't be seeing any talking heads with that config. When a talking head pops up do you get the log message in the chat saying that it was blocked? If-not then the code must not be firing but I couldn't fathom why unless it was modified or somehow being interfered with, which I've never heard of.

**Comment by martin-doychinov** [comment]
I do indeed get the message that a talking head has been blocked every time, but it still shows up.

The only thing I can think of that may interfere with it is Leatrix Plus as it has a similar option to toggle them off (or maybe I'm misinterpreting and it has a different function), it's not toggled on for me when I use the add-on.

**Comment by Xorag** [comment]
There could be some unhooking another addon is doing, is it possible to test with bequiet as your only enabled addon?

**Comment by martin-doychinov** [comment]
Yeah, haven't done that yet. Will try it in a minute.

**Comment by martin-doychinov** [comment]
Ok, I'm fairly certain another addon was interfering. After I disabled everything except bequiet the talking heads do not show up anymore. Tested on about 10 different world quests.

I've also just tested a couple addons I suspected - LeatrixPlus and Weakauras. It wasn't Leatrix, but when I enabled Weakauras (only WA and BQ) the heads started popping up again. So it must be one of the many aura scripts I have which is screwing with BQ.

**Comment by martin-doychinov** [comment]
If I figure out which weakaura is causing issues I can leave a comment here for posterity if you'd like or we can close this down. I've got a bunch of auras though so I don't know how difficult it would be to pinpoint.

**Comment by Xorag** [comment]
bequiet calls the ingame Hide() function against the TalkingHeadFrame. If there is some addon or weakaura that is somehow creating a different frame for the talking head or somehow intercepting Hide() calls on UI elements then i could see this as interfering. Other than going one by one to isolate I don't have any better suggestions. Good luck

**Comment by martin-doychinov** [comment]
Found the weakaura which was interfering - Dragonflight UI Resizer https://wago.io/dI8GCw2bf

**Comment by Xorag** [comment]
cool, you might be able to disable a feature of it, it might be reframing the talking head or something wonky but good to know.

**Comment by martin-doychinov** [comment]
I hope this helps in a small way for debugging and for anybody in the future who might encounter a similar issue. Thank you for taking the time to help me out and also for creating an addon I can't really live without anymore. Those damn talking heads are incredibly annoying.
